version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test-games:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: pip3 install http://github.com/AVEgame/AVE
          name: Install AVE
      - run:
          command: pip3 install pytest
          name: Install pytest
      - python/save-cache
      - run:
          command: python3 -m pytest test/
          name: Run tests

workflows:
  main:
    jobs:
      - test-games
